import jsPDF from 'jspdf'

// PDF styling constants
export const PDF_STYLES = {
  colors: {
    primary: [66, 139, 202] as [number, number, number],
    success: [92, 184, 92] as [number, number, number],
    danger: [217, 83, 79] as [number, number, number],
    text: [40, 40, 40] as [number, number, number],
    textSecondary: [80, 80, 80] as [number, number, number],
    textLight: [120, 120, 120] as [number, number, number]
  },
  fonts: {
    title: 20,
    subtitle: 16,
    heading: 14,
    body: 12,
    small: 10,
    tiny: 8
  },
  spacing: {
    header: 25,
    section: 15,
    line: 10,
    table: 5
  }
}

export const addPDFHeader = (
  doc: jsPDF, 
  title: string, 
  subtitle?: string,
  period?: string
) => {
  const pageWidth = doc.internal.pageSize.width
  let currentY = PDF_STYLES.spacing.header
  
  // Main title
  doc.setFontSize(PDF_STYLES.fonts.title)
  doc.setTextColor(...PDF_STYLES.colors.text)
  doc.text('Sports Club Management', pageWidth / 2, currentY, { align: 'center' })
  currentY += PDF_STYLES.spacing.line
  
  // Report title
  doc.setFontSize(PDF_STYLES.fonts.subtitle)
  doc.text(title, pageWidth / 2, currentY, { align: 'center' })
  currentY += PDF_STYLES.spacing.line
  
  if (subtitle) {
    doc.setFontSize(PDF_STYLES.fonts.body)
    doc.setTextColor(...PDF_STYLES.colors.textSecondary)
    doc.text(subtitle, pageWidth / 2, currentY, { align: 'center' })
    currentY += PDF_STYLES.spacing.line
  }
  
  if (period) {
    doc.text(period, pageWidth / 2, currentY, { align: 'center' })
    currentY += PDF_STYLES.spacing.line
  }
  
  return currentY + PDF_STYLES.spacing.section
}

export const addPDFFooter = (doc: jsPDF) => {
  const pageWidth = doc.internal.pageSize.width
  const pageHeight = doc.internal.pageSize.height
  const footerY = pageHeight - 20
  
  doc.setFontSize(PDF_STYLES.fonts.tiny)
  doc.setTextColor(...PDF_STYLES.colors.textLight)
  doc.text('Generated by Sports Club Management System', pageWidth / 2, footerY, { align: 'center' })
}

export const formatCurrency = (amount: number): string => {
  return `$${Math.abs(amount).toLocaleString()}`
}

export const getFileNameWithDate = (baseName: string): string => {
  const dateStr = new Date().toISOString().split('T')[0]
  return `${baseName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${dateStr}.pdf`
}
